Bump required go version to 1.15
Podman fails to build with go 1.13 with:
```
vendor/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
```
Updating go to 1.15 fixes this issue.
[NO NEW TESTS NEEDED]

Signed-off-by: Dan Čermák <dcermak@suse.com>