test/testvol/main.go: Fix missing arguments to Errorf()
go test -v -p 1 -tags apparmor,ostree,seccomp,selinux,systemd github.com/containers/podman/v2/test/testvol
results in the following error:

> test/testvol/main.go:227:10: Errorf format %s reads arg #1, but call has 0 args
> test/testvol/main.go:233:10: Errorf format %s reads arg #1, but call has 0 args

This patch passes req.Name as an argument to the Errorf() call

Signed-off-by: Raoul Bhatia <raoul.bhatia@radarcs.com>