[v4.0-rhel] Fix AttributeError: cython_sources
Apparent Cython regression causing a warning and traceback when
installing PyYAML with pip:

Ref. Upstream issue 601: https://github.com/yaml/pyyaml/issues/

Ref. warning message:
```
********************************************************************************
The license_file parameter is deprecated, use license_files instead.
By 2023-Oct-30, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************************
```

Ref. traceback snippet:
```
Traceback (most recent call last):
  File "/var/tmp/go/src/github.com/containers/podman/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
...cut...
  File "<string>", line 201, in get_source_files
  File "/tmp/pip-build-env-yiijk0jv/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: cython_sources
```

Signed-off-by: Chris Evich <cevich@redhat.com>