Update suggested commands to view and remove buildah containers
The `podman --rm --storage` command fails to remove these containers with the following error:

```
Error: container "476981d18f08" is mounted and cannot be removed without using force: container state improper
```

The `podman ps --external` command no longer requires `--all` to also be specified since 4.0.0.

Fixes: #20733

Signed-off-by: Gary Yendell <gary.yendell@diamond.ac.uk>