test/e2e: skip "podman cp from ctr chown" for remote
The test fails in podman-remote when copying a file from a container
to an existing file on the host. The remote cp implementation tries
to create a directory at the destination path, resulting in:
  Error: mkdir /tmp/1457882724: not a directory

This is a bug in the remote cp implementation where it doesn't
properly handle copying to an existing file. A fix exists in commit
b0836ab624 (branch cve-441-crio) but hasn't been merged yet.

Skip the test for remote until the fix is integrated.

Signed-off-by: Lokesh Mandvekar <lsm5@redhat.com>