docs: Add missing --url to first podman --remote example
It does not actually work without that argument, looks like the default URL changed or something:

Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:43325/run/user/1000/podman/podman.sock) failed: dial tcp [::1]:43325: connect: connection refused

Signed-off-by: Michael Vorburger ⛑️ <mike@vorburger.ch>