Revert "Cirrus: Enable labeling of EC2 VMs"
Seeing CI failures in VM.keepalive:

   ERROR: Failed to update one or more image timestamps: fedora-aws-etc

This reverts commit 56e7b511e1d1568809e7b4066b97adb2d498fed1.

Signed-off-by: Ed Santiago <santiago@redhat.com>