Cirrus: Avoid build-each-commit check
This check is breaking on PRs and branches, for example:

```
Rebasing (5/24)
error: could not apply e6ed1d4bf... cirrus: update image
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase
--abort".
Could not apply e6ed1d4bf... cirrus: update image
Auto-merging .cirrus.yml
CONFLICT (content): Merge conflict in .cirrus.yml
make: *** [Makefile:269: build-all-new-commits] Error 1
```

Stop running this check rather than debugging/fixing it because this is
a release branch that will not likely ever see a PR containing more than
one commit.

Signed-off-by: Chris Evich <cevich@redhat.com>