test/e2e: skip "podman cp --pid=host file" for remote
Same issue as "podman cp from ctr chown" - the test fails when copying
a file from a container to an existing file on the host. Remote cp
tries to create a directory at the destination, resulting in:
  Error: mkdir /tmp/746758151: not a directory

This is the same bug in the remote cp implementation where it doesn't
handle copying to an existing file path. Fix exists in commit
b0836ab624 but hasn't been merged yet.

Skip the test for remote until the fix is integrated.

Signed-off-by: Lokesh Mandvekar <lsm5@redhat.com>